### ISSUE TITLE
Installation Page: Optional instructions for Touch-ID sudo enable are incorrect

### ISSUE THREAD

**Issue by marceldarvas** [GetOpenStore/getopenstore.github.io#1]
On the [install page](https://getovert.app/install/) instructions appear to be incorrect:
`brew tap homebrew/services`

**`brew install artginzburg/tap/sudo-touchid`**

`sudo brew services start sudo-touchid`

I've highlighted the second line, as it appears to be missing as I ran into an error without following [sudo-touchid](https://github.com/artginzburg/sudo-touchid) instructions!

**Comment by ThatsJustCheesy** [comment]
Thanks for the report!

In the current instructions, I tried to do the installation using Overt (which does the equivalent of `brew install artginzburg/tap/sudo-touchid`). However, since command line is required anyway, perhaps that wasn't the smartest move. My guess is the installation from Overt hadn't finished by the time you ran `sudo brew services …`

For now, I've changed the instructions to be entirely command-line, as you suggested. For the future, I've logged an enhancement:

- GetOvert/Overt#34
